"""Adiciona campos otp_secret e is_mfa_enabled para MFA

Revision ID: d2fea1e99051
Revises: 22ba9c416d84
Create Date: 2025-10-23 10:33:57.142739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2fea1e99051'
down_revision: Union[str, Sequence[str], None] = '22ba9c416d84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_secret', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('is_mfa_enabled', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_mfa_enabled')
    op.drop_column('users', 'otp_secret')
    # ### end Alembic commands ###
